name = "The Hilbert game"
version = "1.1.0"
extra_files = "extras"
intro = "src/intro.lean"

[[worlds]]
name = "Tutorial World"
id = 1
levels = [ "src/tutorial_world/level*.lean" ]

[[worlds]]
name = "Incidence World"
id = 2
parents = [1]
levels = [ "src/incidence_world/level*.lean" ]
