# This is a basic workflow to help you get started with Actions

name: MakeGame

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      production:
        description: 'Deploy to production (default: false). If false, will deploy to test subfolder.'
        required: false
        default: false
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: game.yml
      - name: Update packages
        run: sudo apt install -y unzip make nodejs gettext build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
 
      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;
      - name: Install python Lean dependencies
        run: |
          python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke
      - name: leanpkg configure
        run: leanpkg configure

      - name: get mathlib cache
        run: leanproject get-mathlib-cache || true

      - name: leanpkg build
        id: build
        run: |
          echo "::set-output name=started::true"
          lean --json --make src | python scripts/detect_errors.py
          lean --json --make src | python scripts/detect_errors.py
      - name: Install Game maker
        run: |
          git clone https://github.com/mpedramfar/Lean-game-maker.git
          cd Lean-game-maker/src/interactive_interface
          npm install .
          ./node_modules/.bin/webpack --mode=production
          cd ../..
          pip3 install -e .
      - name : Get server files
        run: |
          VER=`lean -v |sed -nE 's/.*version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/pi'`
          wget -q https://github.com/leanprover-community/lean/releases/download/v$VER/lean-$VER--browser.zip
          unzip *.zip
          mkdir -p "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$VER/"
          cp build/shell/* "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$VER/"
          
      - name: Make game
        run: make-lean-game

      - name: Deploy Production
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.event.inputs.production }}
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./html # The folder the action should deploy.
          single-commit: "true"

      - name: Deploy Test
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ !github.event.inputs.production }}
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./html # The folder the action should deploy.
          target-folder: test/
          single-commit: "false"
